resume_demo/ResumeApp/urls.py
from django.urls import path
from . import views

app_name = "ResumeApp"

urlpatterns = [
    # for class based views we use .as_view(); for function-based view we don't need them
    # homepage
    path('', views.IndexView.as_view(), name="home"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
    path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),

]

resume_demo/resume_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# URL namespaces allow you to uniquely reverse named URL patterns even if different applications use the same URL names.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ResumeApp.urls", namespace="ResumeApp")),
]

# For adding/uploading avatar or photo will be automatically be added in the static and media directory
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume_demo/ResumeApp/models.py
# models are translated into database tables, model name become database name and fields become its columns
# each object saved become each row of that table
from django.db import models
# for user profiles usage
from django.contrib.auth.models import User
# slug for our profile and blog
# importing slugify function
from django.template.defaultfilters import slugify
# can add rich text filed to our blog and profile
from ckeditor.fields import RichTextField


# for coding and key skills columns in index profile page
class Skill(models.Model):

    # name of the skill
    name = models.CharField(max_length=20, blank=True, null=True)
    # score in form of sliding bar of the skill score
    score = models.IntegerField(default=80, blank=True, null=True)
    # images for each key skill will be uploaded to skills folder inside mediafiles directory (created automatically)
    # when uploaded in skill admin page
    image = models.FileField(blank=True, null=True, upload_to="skills")
    # True if is a skill else is a coding skill
    is_key_skill = models.BooleanField(default=False)

    # What a class Meta is, if you're familiar with HTML, meta is just data about something, a web page,
    # or a database table. It doesn't alter the function of the item, it just tells about the data.
    # In HTML, the keywords and description content in the head tag is meta data. It just tells us about the page.
    # In Django, we use meta data about a database table to tell Django things about the database table.
    class Meta:
        # verbose_name_plural: defines the plural name for the object
        # If this isn’t given, Django will use verbose_name + "s".
        # verbose_name and verbose_name_plural:
        # If you're familiar with database tables in Django, you know that the table name should be declared to be a
        # singular form, because in the admin page of Django, it ends with pluralizing the table name.
        # This is because a table is really a representation of objects. So if you declare name such as Comment,
        # it really is a collection of Comments (so Django automatically pluralizes it in the admin page once the
        # database table is created and registered).
        #
        # By default, Django adds a 's' to a table name in the admin page.
        #
        # However, this doesn't always work. For example, if a database table called 'Child',
        # the plural of 'Child' is really 'Children', not 'Childs'.
        # If you create a database table called 'Child' and register it in the admin.py file and go to the admin page,
        # you'll see 'Childs'.
        # So there is a way in Django, you can explicitly declare what the singular form of the database objects
        # should be and what the plural form of the database objects should be.
        # And this can be done by using verbose_name and verbose_name_plural attributes.
        verbose_name_plural = 'Skills'
        # verbose_name is pretty much the equivalent of the label attribute for forms.
        # verbose_name is what is used to give labels to forms.
        verbose_name = 'Skill'

    # returns a skill name
    def __str__(self):
        return self.name


# creating only for one user profile
class UserProfile(models.Model):

    # user field
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # image field (make use of Pillow), will create a folder "avatar" where media file will be saved
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    # uploaded to "cv" directory for uploading files (cv/resume)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'

    # returns first-name and last-name of user model
    # f-strings are evaluated at runtime, you can put any and all valid Python expressions in them.
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


# For contact Page
class ContactProfile(models.Model):

    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        # The default ordering for the object, for use when obtaining lists of objects.
        # This is a tuple or list of strings and/or query expressions.
        # Each string is a field name with an optional “-” prefix, which indicates descending order.
        # Fields without a leading “-” will be ordered ascending. Use the string “?” to order randomly.
        # Ordering is not a free operation. Each field you add to the ordering incurs a cost to your database.
        # Each foreign key you add will implicitly include all of its default orderings as well.
        # If a query doesn’t have an ordering specified, results are returned from the database in an unspecified order.
        # A particular ordering is guaranteed only when ordering by a set of fields that uniquely identify each object
        # in the results. For example, if a name field isn’t unique, ordering by it won’t guarantee objects with the
        # same name always appear in the same order.
        ordering = ["timestamp"]

    def __str__(self):
        return f'{self.name}'


# Testimonial on home page
class Testimonial(models.Model):

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    # if true would show the person's testimonial otherwise not
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    def __str__(self):
        return self.name


# To access Media files and save them in media directory
class Media(models.Model):

    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    # custom save() method
    # save() method from its parent class is to be overridden so we use super keyword.
    # The save method is an inherited method from models.
    # Model which is executed to save an instance into a particular Model.
    # Whenever one tries to create an instance of a model either from
    # admin interface or django shell, save() function is run.
    def save(self, *args, **kwargs):
        # if url exists then is_image validation becomes false
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]

    def __str__(self):
        return self.name


# for portfolio page
class Portfolio(models.Model):

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    # RichTextField is being used by ckeditor
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    # A Slug is basically a short label for something, containing only letters, numbers, underscores or hyphens.
    # They’re generally used in URLs.
    # A "slug" is a way of generating a valid URL, generally using data already obtained.
    # it is created from the title by down-casing all letters, and replacing spaces by hyphens -
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        # we slugify i.e. all letters become small-case and spaces join and become _
        # Be aware that your URL could change when the name field is edited,
        # which can cause broken links. It may be preferable to generate the slug only once when you create a new object
        if not self.id:
            # need to call slugify function to create slug field in Django
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/portfolio/%s/" % self.slug


# same as portfolio page
class Blog(models.Model):

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    # RichTextField is generally used for storing paragraphs that can store any type of data.
    # Rich text is the text that is formatted with common formatting options, such as bold, italics, images, URLs
    # that are unavailable with plain text.
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Blog Profiles'

resume_demo/ResumeApp/forms.py
from django import forms
from .models import ContactProfile

# A widget is Django’s representation of an HTML input element.
# The widget handles the rendering of the HTML, and the extraction of data from a
# \ GET/POST dictionary that corresponds to the widget.
# need to explicitly define the widget we want to assign to a field.


# A ModelForm:
# contact details to display contact in html page
class ContactForm(forms.ModelForm):
    # below are the details what will be rendered in html page
    # class name is the class-name of the form in html frontend-template (we don't actually need them)
    # reason 'name' field's max length is 100 as in modelform of ContactProfile, name is set to 100 likewise others.
    # we are not using 'class': 'form-control' inside our widget declaration as we are not using it in our templates
    name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': '*Full name..'}))
    # max_length=254 is standard for email field
    email = forms.EmailField(max_length=254, required=True, widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
    message = forms.CharField(max_length=1000, required=True, widget=forms.Textarea(attrs={'placeholder': '*Message..',
                                                                                           'rows': 6}))

    class Meta:
        # model which this class represents is ContactProfile
        model = ContactProfile
        # field which we want to render is name, email and message
        fields = ('name', 'email', 'message',)

resume_demo/ResumeApp/views.py
from django.shortcuts import render
# when the form is valid and is saved then message appears saying as Thank You
from django.contrib import messages
from .models import (UserProfile, Blog, Portfolio, Testimonial, Certificate)
# importing generic to use generic views i.e. form views, list views etc. (builtin views)
from django.views import generic
from .forms import ContactForm


# TemplateView: class based generic views to accomplish common tasks.
# It Renders a given template, with the context containing parameters captured in the URL.
# TemplateView should be used when you want to present some information on an HTML page.
# TemplateView should not be used when your page has forms and does creation or update of objects.
# In such cases, FormView, CreateView, or UpdateView is a better option.
# TemplateView is most suitable in the following cases:
# Showing ‘about us’ like pages that are static and hardly need any context.
# Though, it is easy to use context variables with TemplateView.
# Showing pages that work with GET requests and don’t have forms in them.
class IndexView(generic.TemplateView):
    template_name = "ResumeApp/index.html"

    # This method is used to populate a dictionary to use as the template context
    def get_context_data(self, **kwargs):
        # Returns context data for displaying the object
        context = super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        certificates = Certificate.objects.filter(is_active=True)
        blogs = Blog.objects.filter(is_active=True)
        portfolio = Portfolio.objects.filter(is_active=True)

        context["testimonials"] = testimonials
        context["certificates"] = certificates
        context["blogs"] = blogs
        context["portfolio"] = portfolio
        return context


class ContactView(generic.FormView):
    template_name = "ResumeApp/contact.html"
    form_class = ContactForm
    # user will get redirected when the form is valid
    success_url = "/"

    # form valid method
    def form_valid(self, form):
        # save the form instance
        form.save()
        # send the message success
        messages.success(self.request, 'Thank You. We will be in touch Soon.')
        return super().form_valid(form)


class PortfolioView(generic.ListView):
    model = Portfolio
    template_name = "ResumeApp/portfolio.html"
    # django.views.generic.list.ListView provides a builtin way to paginate the displayed list.
    # You can do this by adding a paginate_by attribute to your view class.
    # will show first 2 objects
    paginate_by = 10

    # When you set queryset, the queryset is created only once, when you start your server.
    # On the other hand, the get_queryset method is called for every request.
    # That means that get_queryset is useful if you want to adjust the query dynamically.
    # For example, you could return objects that belong to the current user
    def get_queryset(self):
        # only active portfolios are returned
        return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = "ResumeApp/portfolio-detail.html"


class BlogView(generic.ListView):
    model = Blog
    template_name = "ResumeApp/blog.html"
    paginate_by = 10

    # Used by ListViews - it determines the list of objects that you want to display
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = "ResumeApp/blog-detail.html"

resume_demo/ResumeApp/templates/ResumeApp/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <!-- path to context_processors -->
    <!-- Canonical url is a url that tell search engine ( google, bing etc ) which url is the primary url
    for same content web pages. It is used to fix the duplicate content issue with different webpage url formats.
    So that search engine will know all the url that generate same web content is belongs to one canonical url.
    For example https://www.google.com and https://www.google.com/?abc point to the same web page content,
    so the canonical url for those two pages is https://www.google.com. -->
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'ResumeApp:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!--{% block extend_header %}{% endblock %}-->
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'ResumeApp/partials/messages.html' %}
    {% include 'ResumeApp/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'ResumeApp/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{% endblock %}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

resume_demo/ResumeApp/templates/ResumeApp/contact.html
{% extends 'ResumeApp/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Contact us below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for='name'>Name</label>
            {{form.name}}
            <label for="email">Email</label>
            {{form.email}}
            <label for="subject">Message</label>
            {{form.message}}
            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>

<!-- ================================
End Content
================================= -->
{% endblock %}

resume_demo/ResumeApp/templates/ResumeApp/index.html
{% extends 'ResumeApp/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div>
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}}, <br> a {{me.userprofile.title}}</h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div>
                <div class="col-auto">
                  <a href="{% url 'ResumeApp:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <div class="col-md-auto">
          <div class="keySkillCol">
            <h4 class="smTitle pb-3">Key Skills</h4>
            {% for sk in me.userprofile.skills.all %}
            {% if sk.is_key_skill %}
            <div class="keySkillCard">
              {% if sk.image %}
              <div class="ksIconCol">
                <img src="{{sk.image.url}}" alt="...">
              </div>
              {% endif %}
              <span class="ksText">{{sk.name}}</span>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">Coding Skills</h4>
          <div class="progressCol">
            <div class="progressCard">
              {% for sk in me.userprofile.skills.all %}
              {% if sk.is_key_skill %}
              <div class="progressCol">
                <span class="progressLbl">{{sk.name}}</span>
                <div class="row g-2 align-items-center">
                  <div class="col">
                    <div class="progress progressStyle">
                      <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                  <div class="col-auto">
                    <span class="pLbl">{{sk.score}}%</span>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Certificates</h4>
        </div>

      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.date.date}}</li>
                  <li>{{c.name|title}}</li>
                </ul>
                <p>{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'ResumeApp:portfolios' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'ResumeApp:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'ResumeApp:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
      <div class="testimonialCol">
        <h4 class="smText regular d-block">Testimonials</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for t in testimonials %}
              {% if t.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{{t.thumbnail.url}}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                        <p>{{t.quote}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}

            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>


        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'ResumeApp:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <h4 class="mdTitle cs1Title"><a href="{% url 'ResumeApp:blog' slug=b.slug %}">{{b.name}}</a></h4>
            <ul class="cardOptionCol">
              <li>{{b.timestamp.date}}</li>
              <li>{{b.author}}</li>
            </ul>
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->